/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    categories: Category;
    products: Product;
    'stock-movements': StockMovement;
    customers: Customer;
    'customer-addresses': CustomerAddress;
    'customer-payment-methods': CustomerPaymentMethod;
    'phone-otps': PhoneOtp;
    couriers: Courier;
    orders: Order;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    'stock-movements': StockMovementsSelect<false> | StockMovementsSelect<true>;
    customers: CustomersSelect<false> | CustomersSelect<true>;
    'customer-addresses': CustomerAddressesSelect<false> | CustomerAddressesSelect<true>;
    'customer-payment-methods': CustomerPaymentMethodsSelect<false> | CustomerPaymentMethodsSelect<true>;
    'phone-otps': PhoneOtpsSelect<false> | PhoneOtpsSelect<true>;
    couriers: CouriersSelect<false> | CouriersSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'storefront-home': StorefrontHome;
  };
  globalsSelect: {
    'storefront-home': StorefrontHomeSelect<false> | StorefrontHomeSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  /**
   * Boş bırakırsanız bu bir üst kategoridir (ör. Temel Atıştırmalık). Doluysa alt kategori (ör. Cips).
   */
  parent?: (number | null) | Category;
  name: string;
  /**
   * Boş bırakılırsa kategori adından üretilir.
   */
  slug: string;
  /**
   * Ana sayfa kategori kutularında ve vitrinde kullanılır (isteğe bağlı).
   */
  image?: (number | null) | Media;
  /**
   * Kapalıysa bu kategori (ve vitrinde bağlantıları) online mağazada listelenmez. Altında görünür ürün kalmadıysa da boş kategori gösterilmez.
   */
  showInStorefront?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  barcode: string;
  name: string;
  category: number | Category;
  /**
   * Online mağaza ve ürün listeleri için kapak görseli.
   */
  image?: (number | null) | Media;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  purchasePrice: number;
  salePrice: number;
  vatRate: number;
  stock: number;
  /**
   * Stok bu adedin altına veya eşit düştüğünde kasada uyarı verilir (ürün bazlı; örn. su 50, şampuan 3). 0 = uyarı kapalı.
   */
  lowStockThreshold: number;
  /**
   * Kapalıysa ürün internet mağazasında listelenmez (ör. alkollü içecekler). Kasada satış ayrıca “POS’ta sat” ile yönetilir.
   */
  showInStorefront?: boolean | null;
  /**
   * Kapalıysa barkod ile kasada bu ürün satılamaz.
   */
  showInPos?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Her stok değişimi bir kayıt olarak tutulur. Aynı işlem iki kez tetiklenirse idempotency anahtarı ikinci kaydı engeller.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stock-movements".
 */
export interface StockMovement {
  id: number;
  product: number | Product;
  /**
   * Pozitif: stok artar, negatif: stok azalır.
   */
  delta: number;
  type: 'purchase' | 'sale' | 'refund' | 'order_release' | 'adjustment';
  /**
   * Satış, iade ve sipariş kapanışı hareketlerinde doldurulur.
   */
  order?: (number | null) | Order;
  /**
   * Payload array satırının id değeri (siparişe bağlı hareketlerde).
   */
  orderLineId?: string | null;
  note?: string | null;
  /**
   * Aynı anahtarla ikinci kayıt oluşturulmaz; stok iki kez değişmez.
   */
  idempotencyKey: string;
  recordedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * Tamamlanan satış stoktan düşer. Satır iadesi (İade edilen adet) stoku geri verir. Tam iptal/iade durumunda kalan adetler geri yüklenir.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  orderNumber?: string | null;
  source: 'pos' | 'online';
  /**
   * Online ödeme: müşterinin checkout anındaki tarayıcı origin’i. İyzico callback sonrası başarı/hata sayfası bu hosta yönlendirilir (localhost ile APP_URL farkındayken oturum çerezi korunur).
   */
  checkoutReturnOrigin?: string | null;
  status: 'draft' | 'completed' | 'partially_refunded' | 'cancelled' | 'refunded';
  /**
   * Sadece online siparişlerde anlamlıdır (POS siparişlerinde “uygun değil” kalır). Ödeme tamamlanınca genelde “Hazırlanıyor” ile başlar; kurye çıkınca ve teslimde güncellenir.
   */
  fulfillmentStatus?: ('na' | 'preparing' | 'in_transit' | 'delivered') | null;
  /**
   * POS üzerinden "Sipariş iade kapat" ile true olur; kısmi iade varken listede yanlışlıkla tam iade görünmesini engeller.
   */
  refundClosed?: boolean | null;
  /**
   * İsteğe bağlı (kayıtlı müşteri veya online sipariş)
   */
  customer?: (number | null) | Customer;
  /**
   * Online siparişte teslimatı taşıyacak kurye (mobil ekrandan güncellenir).
   */
  assignedCourier?: (number | null) | Courier;
  items?:
    | {
        product: number | Product;
        quantity: number;
        unitPrice: number;
        /**
         * İade edilmemiş adet × birim fiyat. Kısmi iade sonrası otomatik güncellenir.
         */
        lineTotal: number;
        /**
         * Bu satırdan depoya geri dönen adet (satır bazlı iade).
         */
        quantityRefunded: number;
        id?: string | null;
      }[]
    | null;
  /**
   * Satır kalan tutarlarının toplamı; iade sonrası düşer.
   */
  totalAmount: number;
  /**
   * POS satışlarında kaydedilir.
   */
  paymentMethod?: ('cash' | 'card' | 'credit') | null;
  /**
   * Sadece nakit ödemede.
   */
  cashReceived?: number | null;
  /**
   * Nakit ödemede hesaplanan para üstü.
   */
  changeGiven?: number | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers".
 */
export interface Customer {
  id: number;
  name: string;
  /**
   * Normalize edilmiş numara; giriş eşleştirmesi için.
   */
  phoneKey?: string | null;
  phone?: string | null;
  email?: string | null;
  /**
   * Çoklu adres için “Müşteri adresleri” kullanın.
   */
  address?: string | null;
  /**
   * Online mağaza favorileri.
   */
  favoriteProducts?: (number | Product)[] | null;
  marketingEmail?: boolean | null;
  marketingSms?: boolean | null;
  orderStatusSms?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Kurye kaydı. Mobil ekran adresi: /kurye/[erişim anahtarı]. Yeni kayıtta anahtar otomatik üretilir.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "couriers".
 */
export interface Courier {
  id: number;
  name: string;
  phone: string;
  /**
   * İsteğe bağlı (motosiklet plakası vb.).
   */
  plate?: string | null;
  /**
   * Atanmış aktif teslimat (hazırlanıyor / yolda) varken otomatik kapanır; teslimde tekrar açılır.
   */
  isAvailable?: boolean | null;
  /**
   * Kurye telefonundan açılacak adres: /kurye/[bu değer]. Güvenlik için paylaşmayın.
   */
  accessToken?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customer-addresses".
 */
export interface CustomerAddress {
  id: number;
  customer: number | Customer;
  title: string;
  fullAddress: string;
  city?: string | null;
  district?: string | null;
  isDefault?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customer-payment-methods".
 */
export interface CustomerPaymentMethod {
  id: number;
  customer: number | Customer;
  label: string;
  type: 'card' | 'other';
  /**
   * Sadece gösterim; tam kart numarası saklanmaz.
   */
  last4?: string | null;
  cardBrand?: ('visa' | 'mastercard' | 'troy' | 'other') | null;
  isDefault?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Geçici doğrulama kodları. Üretimde düzenlemeyin.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "phone-otps".
 */
export interface PhoneOtp {
  id: number;
  phoneKey: string;
  codeHash: string;
  expiresAt: string;
  lastSentAt?: string | null;
  verifyAttempts?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'stock-movements';
        value: number | StockMovement;
      } | null)
    | ({
        relationTo: 'customers';
        value: number | Customer;
      } | null)
    | ({
        relationTo: 'customer-addresses';
        value: number | CustomerAddress;
      } | null)
    | ({
        relationTo: 'customer-payment-methods';
        value: number | CustomerPaymentMethod;
      } | null)
    | ({
        relationTo: 'phone-otps';
        value: number | PhoneOtp;
      } | null)
    | ({
        relationTo: 'couriers';
        value: number | Courier;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  parent?: T;
  name?: T;
  slug?: T;
  image?: T;
  showInStorefront?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  barcode?: T;
  name?: T;
  category?: T;
  image?: T;
  description?: T;
  purchasePrice?: T;
  salePrice?: T;
  vatRate?: T;
  stock?: T;
  lowStockThreshold?: T;
  showInStorefront?: T;
  showInPos?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stock-movements_select".
 */
export interface StockMovementsSelect<T extends boolean = true> {
  product?: T;
  delta?: T;
  type?: T;
  order?: T;
  orderLineId?: T;
  note?: T;
  idempotencyKey?: T;
  recordedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers_select".
 */
export interface CustomersSelect<T extends boolean = true> {
  name?: T;
  phoneKey?: T;
  phone?: T;
  email?: T;
  address?: T;
  favoriteProducts?: T;
  marketingEmail?: T;
  marketingSms?: T;
  orderStatusSms?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customer-addresses_select".
 */
export interface CustomerAddressesSelect<T extends boolean = true> {
  customer?: T;
  title?: T;
  fullAddress?: T;
  city?: T;
  district?: T;
  isDefault?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customer-payment-methods_select".
 */
export interface CustomerPaymentMethodsSelect<T extends boolean = true> {
  customer?: T;
  label?: T;
  type?: T;
  last4?: T;
  cardBrand?: T;
  isDefault?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "phone-otps_select".
 */
export interface PhoneOtpsSelect<T extends boolean = true> {
  phoneKey?: T;
  codeHash?: T;
  expiresAt?: T;
  lastSentAt?: T;
  verifyAttempts?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "couriers_select".
 */
export interface CouriersSelect<T extends boolean = true> {
  name?: T;
  phone?: T;
  plate?: T;
  isAvailable?: T;
  accessToken?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  orderNumber?: T;
  source?: T;
  checkoutReturnOrigin?: T;
  status?: T;
  fulfillmentStatus?: T;
  refundClosed?: T;
  customer?: T;
  assignedCourier?: T;
  items?:
    | T
    | {
        product?: T;
        quantity?: T;
        unitPrice?: T;
        lineTotal?: T;
        quantityRefunded?: T;
        id?: T;
      };
  totalAmount?: T;
  paymentMethod?: T;
  cashReceived?: T;
  changeGiven?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Ana sayfa hero ve sıralı bölümler (kategori şeridi, ürün rafları, banner). Boş bölüm bırakılabilir.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "storefront-home".
 */
export interface StorefrontHome {
  id: number;
  heroTitle?: string | null;
  heroSubtitle?: string | null;
  heroImage?: (number | null) | Media;
  heroHref?: string | null;
  sections?:
    | (
        | {
            title?: string | null;
            categories: (number | Category)[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'categoryStrip';
          }
        | {
            title?: string | null;
            products: (number | Product)[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'productShelf';
          }
        | {
            image: number | Media;
            title?: string | null;
            href?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'banner';
          }
      )[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "storefront-home_select".
 */
export interface StorefrontHomeSelect<T extends boolean = true> {
  heroTitle?: T;
  heroSubtitle?: T;
  heroImage?: T;
  heroHref?: T;
  sections?:
    | T
    | {
        categoryStrip?:
          | T
          | {
              title?: T;
              categories?: T;
              id?: T;
              blockName?: T;
            };
        productShelf?:
          | T
          | {
              title?: T;
              products?: T;
              id?: T;
              blockName?: T;
            };
        banner?:
          | T
          | {
              image?: T;
              title?: T;
              href?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}